/*
 * This program is used to calculate the price of Pizza, considering it's diameter, labour and rent.
*Made by Tarkan Dahi on the 26th of Feburary.
 */

/**
 *
 * @author TaDah5199
 */
public class PizzaFrm extends javax.swing.JFrame {

    /**
     * Creates new form PizzaFrm
     */
    public PizzaFrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Titlelbl = new javax.swing.JLabel();
        Diameterlbl = new javax.swing.JLabel();
        Diametertxt = new javax.swing.JTextField();
        Calculationbtn = new javax.swing.JButton();
        SubtotalPromptlbl = new javax.swing.JLabel();
        TaxesPromptlbl = new javax.swing.JLabel();
        TotalPromptlbl = new javax.swing.JLabel();
        SubTotallbl = new javax.swing.JLabel();
        Taxlbl = new javax.swing.JLabel();
        Totallbl = new javax.swing.JLabel();
        outputMessagelbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Titlelbl.setText("Tarkan's Pizza Shop");

        Diameterlbl.setText("Diameter of Pizza (cm)");

        Diametertxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiametertxtActionPerformed(evt);
            }
        });

        Calculationbtn.setText("Calculate");
        Calculationbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculationbtnActionPerformed(evt);
            }
        });

        SubtotalPromptlbl.setText("Subtotal");

        TaxesPromptlbl.setText("Tax");

        TotalPromptlbl.setText("Total");

        SubTotallbl.setText("$0.00");

        Taxlbl.setText("$0.00");

        Totallbl.setText("$0.00");

        outputMessagelbl.setText("Enjoy Your Pizza!");

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(Titlelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Diameterlbl)
                                        .addGap(67, 67, 67)
                                        .addComponent(Diametertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(SubtotalPromptlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TaxesPromptlbl)
                                            .addComponent(TotalPromptlbl))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(SubTotallbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Totallbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Taxlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1)
                                    .addComponent(Calculationbtn))))
                        .addGap(0, 44, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(outputMessagelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Titlelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Diameterlbl)
                    .addComponent(Diametertxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Calculationbtn))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubtotalPromptlbl)
                    .addComponent(SubTotallbl))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TaxesPromptlbl)
                    .addComponent(Taxlbl)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalPromptlbl)
                    .addComponent(Totallbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(outputMessagelbl)
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DiametertxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiametertxtActionPerformed

    }//GEN-LAST:event_DiametertxtActionPerformed

    private void CalculationbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculationbtnActionPerformed
        
       double diameter;
       double labourRent = 1.74;
       
       double pricePizza;
       double subTotal;
       
       double tax;
       double taxRoundOff;
       
       double total;
       double totalRoundOff;
       
       
       diameter = Integer.parseInt(Diametertxt.getText());
       
       
      if (diameter <=20)     
      {
        outputMessagelbl.setText("We are going to make you a cute little pizza!");
        pricePizza = 0.5 * diameter;
        subTotal = pricePizza + labourRent;
        
        tax = subTotal * 0.13;
        taxRoundOff = Math.round(tax * 100.0) / 100.0;
        
        total = subTotal + tax;
        totalRoundOff = Math.round(total * 100.0) / 100.0;
        
        Taxlbl.setText("$" + taxRoundOff);
        SubTotallbl.setText("$" + subTotal );
        Totallbl.setText("$" + totalRoundOff);
      }
      
      else if (diameter <=40)     
      {
        outputMessagelbl.setText("This will be delicious!");
        pricePizza = 0.5 * diameter;
        subTotal = pricePizza + labourRent;
        
        tax = subTotal * 0.13;
        taxRoundOff = Math.round(tax * 100.0) / 100.0;
        
        total = subTotal + tax;
        totalRoundOff = Math.round(total * 100.0) / 100.0;
        
        Taxlbl.setText("$" + taxRoundOff);
        SubTotallbl.setText("$" + subTotal );
        Totallbl.setText("$" + totalRoundOff);
      }
      
      else if (40 <= diameter)     
      {
        outputMessagelbl.setText("Whoa, big pizza! You might need a truck to get this home!");
        pricePizza = 0.5 * diameter;
        subTotal = pricePizza + labourRent;
        
        tax = subTotal * 0.13;
        taxRoundOff = Math.round(tax * 100.0) / 100.0;
        
        total = subTotal + tax;
        totalRoundOff = Math.round(total * 100.0) / 100.0;
        
        Taxlbl.setText("$" + taxRoundOff);
        SubTotallbl.setText("$" + subTotal );
        Totallbl.setText("$" + totalRoundOff);
      }
    }//GEN-LAST:event_CalculationbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PizzaFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PizzaFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PizzaFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PizzaFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PizzaFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Calculationbtn;
    private javax.swing.JLabel Diameterlbl;
    private javax.swing.JTextField Diametertxt;
    private javax.swing.JLabel SubTotallbl;
    private javax.swing.JLabel SubtotalPromptlbl;
    private javax.swing.JLabel TaxesPromptlbl;
    private javax.swing.JLabel Taxlbl;
    private javax.swing.JLabel Titlelbl;
    private javax.swing.JLabel TotalPromptlbl;
    private javax.swing.JLabel Totallbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel outputMessagelbl;
    // End of variables declaration//GEN-END:variables
}
